name: cchfv
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core Python dependencies
  - python =3.12
  - pip >=24
  # Extra dependencies
  - biopython
  - ncbi-datasets-cli >=16.40
  - pandas
  - PyYAML
  - requests
  - seqkit
  - snakemake
  - unzip
  - snakefmt
  - tsv-utils
  - augur
  - nextclade
